config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/MrLavaLoba2:
      branch: main
      repo: https://github.com/demichie/MrLavaLoba2/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/MrLavaLoba2 git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-amber-dugong.sh
        container: qc.acc_wheezy-violet-skunk
  QC.Doc:
    repos:
      github.com/demichie/MrLavaLoba2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-lemon-olm.sh
        container: qc.doc_flabby-asparagus-bullfrog
      github.com/demichie/MrLavaLoba2 git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-emerald-hippopotamus.sh
        container: qc.doc_skimpy-chartreuse-squirt
      github.com/demichie/MrLavaLoba2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-magnolia-retriever.sh
        container: qc.doc_crabby-zucchini-armadillo
  QC.Lic:
    repos:
      github.com/demichie/MrLavaLoba2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-gold-opossum.sh
        container: qc.lic_freaky-jade-rabbit
  QC.Met:
    repos:
      github.com/demichie/MrLavaLoba2 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-ivory-mau.sh
        container: qc.met_nippy-ruby-yak
  QC.Sec:
    repos:
      github.com/demichie/MrLavaLoba2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-aquamarine-fish.sh
        container: qc.sec_fuzzy-auburn-mouse
  QC.Sty:
    repos:
      github.com/demichie/MrLavaLoba2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-violet-armadillo.sh
        container: qc.sty_fuzzy-ecru-dugong
  QC.Uni:
    repos:
      github.com/demichie/MrLavaLoba2 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-chestnut-magpie.sh
        container: qc.uni_wiggy-jade-penguin
  QC.Ver:
    repos:
      github.com/demichie/MrLavaLoba2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-apricot-husky.sh
        container: qc.ver_stinky-cerise-beaver
timeout: 5400
