config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/MrLavaLoba2:
      branch: main
      repo: https://github.com/demichie/MrLavaLoba2/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/MrLavaLoba2 git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-grey-harrier.sh
        container: qc.acc_snoopy-linen-anteater
  QC.Doc:
    repos:
      github.com/demichie/MrLavaLoba2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-amaranth-liger.sh
        container: qc.doc_homey-sangria-ocelot
      github.com/demichie/MrLavaLoba2 git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-lilac-dolphin.sh
        container: qc.doc_breezy-tan-worm
      github.com/demichie/MrLavaLoba2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-aquamarine-moth.sh
        container: qc.doc_boozy-zucchini-magpie
  QC.Lic:
    repos:
      github.com/demichie/MrLavaLoba2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-asparagus-akbash.sh
        container: qc.lic_droopy-lilac-koala
  QC.Met:
    repos:
      github.com/demichie/MrLavaLoba2 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-amber-dollar.sh
        container: qc.met_shabby-carmine-moorhen
  QC.Sec:
    repos:
      github.com/demichie/MrLavaLoba2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-chartreuse-tetra.sh
        container: qc.sec_scanty-bistre-tapir
  QC.Sty:
    repos:
      github.com/demichie/MrLavaLoba2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-chartreuse-anteater.sh
        container: qc.sty_foggy-cerise-lemming
  QC.Uni:
    repos:
      github.com/demichie/MrLavaLoba2 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-red-jaguar.sh
        container: qc.uni_foggy-russet-mongoose
  QC.Ver:
    repos:
      github.com/demichie/MrLavaLoba2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-flax-labradoodle.sh
        container: qc.ver_ready-pink-chimpanzee
timeout: 5400
